# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ nodes, stdenv, config, lib, pkgs, callPackage, ... }:
with lib;
rec {
  system.stateVersion = "24.05";

  imports = [
    ./common.nix
    ../../configuration.nix
  ];

      #

  my = {
    hostName = "whittles-iskandar";
    zfs = {
      mirrorDrives = [
        "nvme-CT2000T500SSD8_240646EA4ECB"
        "nvme-WD_BLACK_SN850X_HS_2000GB_24120D800169"
      ];
      partitions = {
        legacyBIOS = 1;
        EFI        = 2;
        boot       = 3;
        main       = 4;
        swap       = 5;
      };
      pools = let id = "vfwzza"; in {
        boot.name = "boot-${id}";
        main.name = "main-${id}";
      };
      usersZvolsForVMs = [
      ];
    };
    role = {
      architecture = true;
      desktop = true;
      development = {
        nix = true;
        clojure = true;
      };
      digitalArt = true;
      gaming = true;
      mediaArchival = true;
      modeling3D = true;
      textiles = true;
    };
    services = {
      printing3D = true;
      synergy.server = {
        enable = true;
        serverScreen = "left";
        clientScreen = "right";
        clientNode = nodes.alex-laptop;
      };
      anki = true;
      calibre = true;
      nextCloud = false;
      plex = true;
      mediaRoot = "/media";
      webDomain = "tmp";
      adminEmail = "tmp";
      adminPassword = "tmp";
    };
    allowedUnfree = [
      "nvidia-X11"
    ];
  };

  hardware.bluetooth.enable = true;

  boot = {
    initrd.availableKernelModules = [
      "ahci"
      "nvme"
      "sd_mod"
      "sr_mod"
      "usb_storage"
      "usbhid"
      "xhci_pci"
    ];

    blacklistedKernelModules = [
      "sp5100-tco" # Suppress a warning at boot. The Asus X570 does not support IPMI.
    ];

    kernelModules = [
      "lm92" # Temp sensors (NVIDIA)
      "sg"   # Blu-ray ODD
    ];
    extraModulePackages = [ ];

    zfs.extraPools = [ "tank" ];
  };

  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };

  hardware.nvidia = {
    modesetting.enable = true;
    nvidiaSettings = true;
    package = config.boot.kernelPackages.nvidiaPackages.beta;
  };

  nix.settings.max-jobs = 14;
  powerManagement.cpuFreqGovernor = "performance";

}
